version: "2"
services:
  grafana:
    image: grafana/grafana
    volumes: 
      - ./grafana/data:/var/lib/grafana
    links:
      - influxdb
    ports:
      - 3000:3000
  
  influxdb:
    image: influxdb
    volumes: 
      - ./influxdb/data:/var/lib/influxdb
    environment: 
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=xjvw43sfd
      - INFLUXDB_READ_USER=reader
      - INFLUXDB_READ_USER_PASSWORD=xcv2klxp
    ports: 
      - 127.0.0.1:8086:8086
      - 127.0.0.1:8083:8083